version: "3"
services:
    rodo-api:
        container_name: rodo-api
        build:
            context: .
            dockerfile: Dockerfile
        # expose:
        #     - "3000"
        # expose alleen als we een db service gaan toevoegen
        ports:
            - "8181:8181"
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro