version: "3"
services:
    rodo-api:
        container_name: rodo-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8181:8181"
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./certs:/etc/nginx/certs:ro
    certbot:
        image: certbot/certbot
        volumes:
        - ./certs:/etc/letsencrypt
        - ./certbot:/var/www/certbot
        command: certbot certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d ${DOMAIN} --quiet
        entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"